### ISSUE TITLE
Can't add multiple flavors of port

### ISSUE THREAD

**Issue by neilalexander** [ocochard/BSDRP#24]
For example, targeting BSDRP 1.91, I want to install bird 1.6.4 instead of bird 2.x.

There is a `net/bird` port for FreeBSD 11 which seems to support `FLAVOR=ipv4` and `FLAVOR=ipv6` as flavors, and apparently the separate `net/bird6` port is no longer in existence. I want to install both flavors in the image.

In my .nano file I tried the following:
```
add_port "net/bird" "FLAVOR=ipv4"
add_port "net/bird" "FLAVOR=ipv6"
```
... but only one or other gets installed, leaving it impossible to install both `bird` and `bird6`.

I guess this is because the working directory/mount for `net/bird` is overwritten on the second pass.

**Comment by lrizzi** [comment]
I got the same issue, I still use bird 1.6.x in my production environment (@ocochard btw, thanks for this project)

Anyway updating the `make.sh` script to support multiple flavor will be quite tricky because it use the port name for everything (find the source, build, temp directory, etc.)

I've found out a quick and dirty workaround, just make a symlink of the `net/bird` port directory: `/BSDRP/BSDRP/FreeBSD/ports/net/bird` like this `/BSDRP/BSDRP/FreeBSD/ports/net/bird6` for example and then recall it into your .nano:

```
add_port "net/bird" "FLAVOR=ipv4"
add_port "net/bird6" "FLAVOR=ipv6"
```

**Comment by ocochard** [comment]
Oops, thanks to @lrizzi a solution was provided.
